name: valuefinder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  injectable: ^2.1.0

  firebase_core: ^3.2.0 # Firebase core
  # cloud_firestore: ^5.1.0 # Firebase store for database related
  firebase_storage: ^12.1.1 # For storage services
  image_picker: ^1.1.2 # Image picker   
  gallery_saver: ^2.3.2 # Gallery saver
  # image_cropper: ^4.0.1 # Image cropper
  camera: ^0.11.0+1
  gap: ^3.0.1
  external_path: ^1.0.3
  media_scanner: ^2.1.0

  #state management
  flutter_bloc: ^8.1.4

  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.0
  injectable_generator: ^2.1.0
  equatable: ^2.0.5
  # testing purpose
  mockito: ^5.0.15
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/splash_image.png
    - assets/main_image.png
