// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQV4Cyk_i4bXGjzCGiqy5nec_QJPAp1EY',
    appId: '1:1002412293801:web:25a0fe1b20c2dd3e52b3b8',
    messagingSenderId: '1002412293801',
    projectId: 'excelly-startup',
    authDomain: 'excelly-startup.firebaseapp.com',
    storageBucket: 'excelly-startup.appspot.com',
    measurementId: 'G-QL5VW7SSDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9ZteqRe39bf8uM2vU9y6P0e-yXdWWWU',
    appId: '1:1002412293801:android:ed8759d7a063613652b3b8',
    messagingSenderId: '1002412293801',
    projectId: 'excelly-startup',
    storageBucket: 'excelly-startup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvxXuxZSB6E-WxjQyMdCE7naCyFcQyDM',
    appId: '1:1002412293801:ios:01fd7a2f0e1bf87852b3b8',
    messagingSenderId: '1002412293801',
    projectId: 'excelly-startup',
    storageBucket: 'excelly-startup.appspot.com',
    iosBundleId: 'com.example.valuefinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIvxXuxZSB6E-WxjQyMdCE7naCyFcQyDM',
    appId: '1:1002412293801:ios:01fd7a2f0e1bf87852b3b8',
    messagingSenderId: '1002412293801',
    projectId: 'excelly-startup',
    storageBucket: 'excelly-startup.appspot.com',
    iosBundleId: 'com.example.valuefinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQV4Cyk_i4bXGjzCGiqy5nec_QJPAp1EY',
    appId: '1:1002412293801:web:25a0fe1b20c2dd3e52b3b8',
    messagingSenderId: '1002412293801',
    projectId: 'excelly-startup',
    authDomain: 'excelly-startup.firebaseapp.com',
    storageBucket: 'excelly-startup.appspot.com',
    measurementId: 'G-QL5VW7SSDQ',
  );

}